### ISSUE TITLE
❓ Question - Include patches in build time for non-root devices?

### ISSUE THREAD

**Issue by Charlyo** [Rikj000/Android-Auto-XLauncher-Unlocked#2]
Hello @Rikj000 and thank you for this amazing patches. I Do not plan to have a rooted / bootloader unlocked but It would be nice to make sure 3rd party apps can be used with android auto. I do my own android builds with microg. 

Is it possible to come up with the [same patches](https://github.com/Rikj000/Android-Auto-XLauncher-Unlocked/blob/development/app/src/main/java/com/google/android/projection/gearhead/xunlocked/AAXUnlock.java) without needing xposed for an aosp build?

Thank you

**Comment by Rikj000** [comment]
Hi @Charlyo

You could de-compile the Android Auto app,
look for the functions being hooked, patch those in a similar way,
re-package the app, uninstall the original and install the patched version instead.

This method is inferior compared to the Xposed hooks though,
because you'll have to manually re-patch each AA update,
and AA updates are enforced upon users.

The Xposed hooks realize the same thing, without modifying AA itself,
which makes updating AA easy and re-patching not required.

**Comment by Rikj000** [comment]
Doubt that this will be possible on ROMs with an existing AndroidAuto stub `.apk` in the system partition though.
Because the `.apk` signature will be different, which will likely block you from installing a patched version.

Unless you also re-package the stub with the same signature as your modified AA `.apk`,
and then include that in the system partition of a ROM you've build yourself,
which is a lot of work, and will require an unlocked bootloader to initially flash the ROM,
but root / xposed will not be required.

To simply work around the `.apk` signature checks, you can look into another Xposed module, [Core Patch](https://github.com/LSPosed/CorePatch),
which disables signature verification, but does require root / xposed.

**Comment by Rikj000** [comment]
Lastly, for non-rooted devices, if you want to keep it simple, check the [honorable mentions](https://github.com/Rikj000/Android-Auto-XLauncher-Unlocked#honorable-mentions)

With KingInstaller, AA-Store, AAAD and AAEase,
you should be able to already get a decent amount of 3th party apps working on a non-rooted device.
Likely not all of them though.

**Comment by Charlyo** [comment]
Thank you @Rikj000 for the explanations!!!

Unfortunatelly king installer is not working for me (android 13). It still says it was installed by KingIInstaller

**Comment by Rikj000** [comment]
> Unfortunatelly king installer is not working for me (android 13). It still says it was installed by KingInstaller

Give AA-Store, AAAD and AAEase a try, if those don't work either,
you'll have to take the hard route described above,
or go the root / xposed way.

Closing this issue due to the question being answered.

**Comment by Charlyo** [comment]
Thanks, @Rikj000 !
